### ISSUE TITLE
Table 1

### ISSUE THREAD

**Issue by mvdh7** [mvdh7/foram#10]
- [x] k+1
  - [x] k-1 - Ben
  - [x] k+4 - Siham
  - [x] k-4 - Lennart
  - [x] k+5
  - [x] k-5
  - [x] k+6
  - [x] k-6
  - [x] k+7
  - [x] k-7
  
  - [x] K1
  - [x] K2
  - [x] Kw
  - [x] KB

**Comment by sihamForam** [comment]
I'm starting to work on K2

**Comment by sihamForam** [comment]
moving on to k-5

**Comment by sihamForam** [comment]
k+7 is next

**Comment by mvdh7** [comment]
I am doing KB
